/**
 * Shared image utilities for product image handling.
 * This is the single source of truth for filtering dummy images, normalising
 * image arrays, selecting the primary image, and generating fallback letters.
 */

const DUMMY_IMAGE_PATTERNS = [
  "KeyDiy.png",
  "Lonsdor.png",
  "Xhorse.png",
  "GTL.png",
];

export const S3_BUCKET_URL = "https://allremotes.s3.ap-southeast-2.amazonaws.com";

/**
 * Filter out S3 placeholder URLs that were generated by the old enrichment logic.
 * It removes URLs matching https://allremotes.s3.../images/{sku}-N.png where N > 1,
 * while keeping sku-1.png. This prevents broken -2..-5 placeholders from showing.
 */
export function filterS3GeneratedPlaceholders(images: unknown[], sku: string | undefined): string[] {
  if (!Array.isArray(images) || !sku || !sku.trim()) return images as string[];
  const normalizedSku = sku.trim();
  const firstUrl = `${S3_BUCKET_URL}/images/${normalizedSku}-1.png`;
  const hasFirstUrl = images.some((img) => typeof img === "string" && img === firstUrl);

  if (!hasFirstUrl) return images as string[];

  return images.filter((img) => {
    if (typeof img !== "string") return true;
    const match = img.match(new RegExp(`^${S3_BUCKET_URL.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/images/${normalizedSku.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}-(\\d+)\\.png$`));
    if (!match) return true;
    const index = parseInt(match[1], 10);
    return index <= 1;
  }) as string[];
}

/**
 * Filter out dummy brand images from an image array.
 * Empty / non-string values are also removed.
 */
export function filterDummyImages(images: unknown[]): string[] {
  if (!Array.isArray(images)) return [];

  return images
    .filter((img): img is string => typeof img === "string" && img.trim().length > 0)
    .filter((img) => {
      const filename = img.split("/").pop();
      if (!filename) return true;
      return !DUMMY_IMAGE_PATTERNS.includes(filename);
    });
}

/**
 * Get all displayable images for a product.
 * Combines the `images` array and the single `image` field, removes dummies,
 * and preserves order with no duplicates.
 */
export function getProductImages(product: any): string[] {
  if (!product) return [];

  const images: string[] = [];

  if (Array.isArray(product.images)) {
    product.images.forEach((img: unknown) => {
      if (typeof img === "string" && img.trim() && !images.includes(img)) {
        images.push(img);
      }
    });
  }

  if (
    typeof product.image === "string" &&
    product.image.trim() &&
    !images.includes(product.image)
  ) {
    images.push(product.image);
  }

  return filterDummyImages(images);
}

/**
 * Get the primary image for a product.
 * Returns the first non-dummy image, or an empty string.
 */
export function getPrimaryImage(product: any): string {
  const images = getProductImages(product);
  return images[0] || "";
}

/**
 * Get the fallback letter to show when a product image is missing or broken.
 */
export function getFallbackLetter(product: any): string {
  const brand = product?.brand?.trim() || "";
  const name = product?.name?.trim() || product?.model?.trim() || "";
  const fallback = brand || name || "R";
  return fallback.charAt(0).toUpperCase();
}
